Terraform Provider v5 Support
cloudposse/terraform-aws-s3-website pull request #93
Opened 2023-07-24 22:53 UTC by milldr

## what
- Terraform v5 updates
- Support for new S3 bucket requirements

## why
- Updates to requirements for CI checks
- Set bucket ownership and grants instead of `public-read` ACL to satisfy new S3 requirements

## references
- closes #92 
- closes #91
- closes #89 
- closes #88

2023-07-24 22:59 UTC, milldr commented
/terratest

2023-07-24 23:03 UTC, milldr commented
/terratest

2023-07-24 23:08 UTC, milldr commented
/terratest

2023-07-24 23:13 UTC, milldr commented
/terratest

2023-07-25 05:23 UTC, Nuru requested changes
Convert to pass-through to [terraform-aws-s3-bucket](https://github.com/cloudposse/terraform-aws-s3-bucket) so we can archive this module. s3-bucket should already have all the necessary features, and if not, add them there. LMK if it is too much work.

2023-07-25 06:51 UTC, milldr commented on examples/complete/versions.tf
> +      version = ">= 4.9"
added

2023-07-25 06:52 UTC, milldr commented
> Convert to pass-through to [terraform-aws-s3-bucket](https://github.com/cloudposse/terraform-aws-s3-bucket) so we can archive this module. s3-bucket should already have all the necessary features, and if not, add them there. LMK if it is too much work.

We decided that we will leave this as a final PR for the module, and redirect users to use the `s3-bucket` module instead. See the README and linked module in this PR description

2023-07-25 06:53 UTC, milldr commented
/terratest

2023-07-25 06:54 UTC, milldr commented
Labeled as a major release to call attention to final PR

2023-08-02 06:19 UTC, Nuru commented
/terratest

2023-08-02 06:19 UTC, Nuru approved these changes

2023-08-02 06:23 UTC, merged